module.exports = {
  INVENTORY: {
    GET_ITEMS_REQUEST: 'INVENTORY_GET_ITEMS_REQUEST',
    GET_ITEMS_FAILURE: 'INVENTORY_GET_ITEMS_FAILURE',
    GET_ITEMS_SUCCESS: 'INVENTORY_GET_ITEMS_SUCCESS',
    UPDATE_ITEM_REQUEST: 'INVENTORY_UPDATE_ITEM_REQUEST',
    UPDATE_ITEM_FAILURE: 'INVENTORY_UPDATE_ITEM_FAILURE',
    UPDATE_ITEM_SUCCESS: 'INVENTORY_UPDATE_ITEM_SUCCESS',
    CREATE_ITEM_REQUEST: 'INVENTORY_CREATE_ITEM_REQUEST',
    CREATE_ITEM_FAILURE: 'INVENTORY_CREATE_ITEM_FAILURE',
    CREATE_ITEM_SUCCESS: 'INVENTORY_CREATE_ITEM_SUCCESS',
    INIT_INVENTORY_SUCCESS: 'INVENTORY_INIT_INVENTORY_SUCCESS'
  },
  TRANSACTION: {
    UPDATE_TRANSACTIONS: 'TRANSACTION_UPDATE_TRANSACTIONS',
    ORDER_REQUEST: 'TRANSACTION_ORDER_REQUEST',
    ORDER_FAILURE: 'TRANSACTION_ORDER_FAILURE',
    ORDER_SUCCESS: 'TRANSACTION_ORDER_SUCCESS',
    RESTOCK_REQUEST: 'TRANSACTION_RESTOCK_REQUEST',
    RESTOCK_FAILURE: 'TRANSACTION_RESTOCK_FAILURE',
    RESTOCK_SUCCESS: 'TRANSACTION_RESTOCK_SUCCESS'
  }
};
