module.exports = {
  INVENTORY: {
    GET_ITEMS_REQUEST: 'INVENTORY_GET_ITEMS_REQUEST',
    GET_ITEMS_FAILURE: 'INVENTORY_GET_ITEMS_FAILURE',
    GET_ITEMS_SUCCESS: 'INVENTORY_GET_ITEMS_SUCCESS'
  },
  TRANSACTION: {
    ORDER_REQUEST: 'TRANSACTION_ORDER_REQUEST',
    ORDER_FAILURE: 'TRANSACTION_ORDER_FAILURE',
    ORDER_SUCCESS: 'TRANSACTION_ORDER_SUCCESS'
  }
};
